"""Initial Group Model

Revision ID: 538d9a82c878
Revises: 015a18e9326c
Create Date: 2024-08-06 10:59:32.708071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '538d9a82c878'
down_revision: Union[str, None] = '015a18e9326c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('department', sa.Enum('ECONOMIST', 'INFORMATION_SYSTEMS_SPECIALIST', 'WEB_DEVELOPER', 'LANDSCAPE_DESIGNER', 'LIGHT_INDUSTRY_WORKER', 'HAIRDRESSER', 'COSMETOLOGIST', 'DESIGNER', 'FIRE_FIGHTER', 'BUILDER', 'BIM_SPECIALIST', 'BANKER', 'FINANCIER', 'WELDER', 'BAKER_PASTRY_CHEF', 'INDUSTRIAL_FURMITURE_DESIGNER', 'INTERIOR_DESIGNER', 'GENERAL_CONSTRUCTION_WORKER', 'ATOMIC_ENGINEER', name='department'), nullable=False),
    sa.Column('cource_number', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('cource_number >= 1 AND cource_number <= 4', name='cource_number_range'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('band_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table('band_members')
    op.drop_table('group')
    # ### end Alembic commands ###
