"""Applications

Revision ID: 0c79bec7dcf0
Revises: d6b05255152b
Create Date: 2024-09-19 12:08:01.531577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c79bec7dcf0'
down_revision: Union[str, None] = 'd6b05255152b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GROUP_JOIN', 'BECOME_ELDER', name='applicationtype'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'ADOPTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('sending_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('last_update_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['sending_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
