"""Departament Rename

Revision ID: 067d725d9fed
Revises: 7c45ead5db9c
Create Date: 2024-08-09 12:09:03.209919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '067d725d9fed'
down_revision: Union[str, None] = '7c45ead5db9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Определение Enum типа specialization
specialization_enum = postgresql.ENUM(
    'ECONOMIST', 
    'INFORMATION_SYSTEMS_SPECIALIST', 
    'WEB_DEVELOPER', 
    'LANDSCAPE_DESIGNER', 
    'LIGHT_INDUSTRY_WORKER', 
    'HAIRDRESSER', 
    'COSMETOLOGIST', 
    'DESIGNER', 
    'FIRE_FIGHTER', 
    'BUILDER', 
    'BIM_SPECIALIST', 
    'BANKER', 
    'FINANCIER', 
    'WELDER', 
    'BAKER_PASTRY_CHEF', 
    'INDUSTRIAL_FURNITURE_DESIGNER', 
    'INTERIOR_DESIGNER', 
    'GENERAL_CONSTRUCTION_WORKER', 
    'ATOMIC_ENGINEER', 
    name='specialization'
)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем тип specialization
    specialization_enum.create(op.get_bind(), checkfirst=True)
    
    # Добавляем столбец specialization
    op.add_column('groups', sa.Column('specialization', specialization_enum, nullable=False))
    
    # Удаляем столбец department
    op.drop_column('groups', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем обратно столбец department
    op.add_column('groups', sa.Column('department', sa.Enum('ECONOMIST', 'INFORMATION_SYSTEMS_SPECIALIST', 'WEB_DEVELOPER', 'LANDSCAPE_DESIGNER', 'LIGHT_INDUSTRY_WORKER', 'HAIRDRESSER', 'COSMETOLOGIST', 'DESIGNER', 'FIRE_FIGHTER', 'BUILDER', 'BIM_SPECIALIST', 'BANKER', 'FINANCIER', 'WELDER', 'BAKER_PASTRY_CHEF', 'INDUSTRIAL_FURNITURE_DESIGNER', 'INTERIOR_DESIGNER', 'GENERAL_CONSTRUCTION_WORKER', 'ATOMIC_ENGINEER', name='department'), autoincrement=False, nullable=False))
    
    # Удаляем столбец specialization
    op.drop_column('groups', 'specialization')
    
    # Удаляем тип specialization
    specialization_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
