"""DataBase creation

Revision ID: d6b05255152b
Revises: 
Create Date: 2024-09-16 12:50:54.188310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b05255152b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('specialization', sa.Enum('ECONOMIST', 'INFORMATION_SYSTEMS_SPECIALIST', 'WEB_DEVELOPER', 'LANDSCAPE_DESIGNER', 'LIGHT_INDUSTRY_WORKER', 'HAIRDRESSER', 'COSMETOLOGIST', 'DESIGNER', 'FIRE_FIGHTER', 'BUILDER', 'BIM_SPECIALIST', 'BANKER', 'FINANCIER', 'WELDER', 'BAKER_PASTRY_CHEF', 'INDUSTRIAL_FURNITURE_DESIGNER', 'INTERIOR_DESIGNER', 'GENERAL_CONSTRUCTION_WORKER', 'ATOMIC_ENGINEER', name='specialization'), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('course_number >= 1 AND course_number <= 4', name='course_number_range'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ELDER', 'STUDENT', name='role'), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('users')
    op.drop_table('groups')
    # ### end Alembic commands ###
