"""Update Group Relationship

Revision ID: dcab97cd8634
Revises: 0f18ba14eb86
Create Date: 2024-08-13 10:03:11.848290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcab97cd8634"
down_revision: Union[str, None] = "0f18ba14eb86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_students",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.drop_table("band_members")
    op.add_column("users", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "users", ["group_id"])
    op.create_foreign_key(None, "users", "groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "group_id")
    op.create_table(
        "band_members",
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="band_members_group_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="band_members_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name="band_members_pkey"),
    )
    op.drop_table("group_students")
    # ### end Alembic commands ###
