"""Rename Group Requests on Application

Revision ID: 0f18ba14eb86
Revises: d39bcefacfce
Create Date: 2024-08-12 09:11:24.823913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f18ba14eb86'
down_revision: Union[str, None] = 'd39bcefacfce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GROUP_JOIN', 'BECOME_ELDER', name='applicationtype'), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'ADOPTED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('sending_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('last_update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['sending_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('groups_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('GROUP_JOIN', 'BECOME_ELDER', name='grouprequesttype'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('SENT', 'ADOPTED', 'REJECTED', name='grouprequeststatus'), autoincrement=False, nullable=False),
    sa.Column('requesting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_update_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='groups_requests_group_id_fkey'),
    sa.ForeignKeyConstraint(['requesting_id'], ['users.id'], name='groups_requests_requesting_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='groups_requests_pkey')
    )
    op.drop_table('applications')
    # ### end Alembic commands ###
