"""Initial Group Requests

Revision ID: 6497a3050e20
Revises: 067d725d9fed
Create Date: 2024-08-10 21:00:56.741621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6497a3050e20"
down_revision: Union[str, None] = "067d725d9fed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("GROUP_JOIN", "BECOME_ELDER", name="grouprequesttype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("SENT", "ADOPTED", "REJECTED", name="grouprequeststatus"),
            nullable=False,
        ),
        sa.Column("requesting_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["requesting_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("groups_requests")
    # ### end Alembic commands ###
