"""Initial DB

Revision ID: e011a0203fbb
Revises: 
Create Date: 2024-08-07 09:13:15.140008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e011a0203fbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ELDER', 'STUDENT', name='role'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mailing_consent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('duties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attendant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('department', sa.Enum('ECONOMIST', 'INFORMATION_SYSTEMS_SPECIALIST', 'WEB_DEVELOPER', 'LANDSCAPE_DESIGNER', 'LIGHT_INDUSTRY_WORKER', 'HAIRDRESSER', 'COSMETOLOGIST', 'DESIGNER', 'FIRE_FIGHTER', 'BUILDER', 'BIM_SPECIALIST', 'BANKER', 'FINANCIER', 'WELDER', 'BAKER_PASTRY_CHEF', 'INDUSTRIAL_FURMITURE_DESIGNER', 'INTERIOR_DESIGNER', 'GENERAL_CONSTRUCTION_WORKER', 'ATOMIC_ENGINEER', name='department'), nullable=False),
    sa.Column('cource_number', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('cource_number >= 1 AND cource_number <= 4', name='cource_number_range'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('band_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('band_members')
    op.drop_table('tokens')
    op.drop_table('groups')
    op.drop_table('duties')
    op.drop_table('users')
    # ### end Alembic commands ###
