"""Delete group_students

Revision ID: 71b530e3c18d
Revises: dcab97cd8634
Create Date: 2024-08-13 10:15:02.744719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b530e3c18d'
down_revision: Union[str, None] = 'dcab97cd8634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_students',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='group_students_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='group_students_user_id_fkey'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name='group_students_pkey')
    )
    # ### end Alembic commands ###
