"""Update Group Requests

Revision ID: d39bcefacfce
Revises: 6497a3050e20
Create Date: 2024-08-11 08:39:50.311508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d39bcefacfce"
down_revision: Union[str, None] = "6497a3050e20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups_requests", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "groups_requests", "groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups_requests", type_="foreignkey")
    op.drop_column("groups_requests", "group_id")
    # ### end Alembic commands ###
