"""other models

Revision ID: a11910ce5c05
Revises: 6aee6eefad40
Create Date: 2025-01-23 16:15:07.510015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a11910ce5c05"
down_revision: Union[str, None] = "6aee6eefad40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("GROUP_JOIN", "BECOME_ELDER", name="applicationtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("SENT", "ADOPTED", "REJECTED", name="applicationstatus"),
            nullable=False,
        ),
        sa.Column("sending_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column(
            "last_update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sending_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("applications")
    # ### end Alembic commands ###
