"""other models

Revision ID: 6aee6eefad40
Revises: ad0be57cb650
Create Date: 2025-01-23 16:14:09.349354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6aee6eefad40"
down_revision: Union[str, None] = "ad0be57cb650"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=32), nullable=False),
        sa.Column(
            "specialization",
            sa.Enum(
                "ECONOMIST",
                "INFORMATION_SYSTEMS_SPECIALIST",
                "WEB_DEVELOPER",
                "LANDSCAPE_DESIGNER",
                "LIGHT_INDUSTRY_WORKER",
                "HAIRDRESSER",
                "COSMETOLOGIST",
                "DESIGNER",
                "FIRE_FIGHTER",
                "BUILDER",
                "BIM_SPECIALIST",
                "BANKER",
                "FINANCIER",
                "WELDER",
                "BAKER_PASTRY_CHEF",
                "INDUSTRIAL_FURNITURE_DESIGNER",
                "INTERIOR_DESIGNER",
                "GENERAL_CONSTRUCTION_WORKER",
                "ATOMIC_ENGINEER",
                name="specialization",
            ),
            nullable=False,
        ),
        sa.Column("course_number", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.CheckConstraint(
            "course_number >= 1 AND course_number <= 4", name="course_number_range"
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("creator_id"),
        sa.UniqueConstraint("title"),
    )
    op.add_column("users", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "group_id")
    op.drop_table("groups")
    # ### end Alembic commands ###
